services:
  noteswebapp:
    build:
      context: ./NotesWEBAPP
      dockerfile: Dockerfile


  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: NotesDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: webapplication
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;User Id=postgres;Password=1234;Database=NotesDB"
    depends_on:
      - postgres
    networks:
      - default

volumes:
  postgres-data:

networks:
  default:
